import type { NextPage } from "next";
import Head from "next/head";
import { Props } from "../interfaces";

const Home: NextPage<Props> = ({ product }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {product?.length === 0 ? (
        <div>Loading...</div>
      ) : (
        product?.map(({ id, name, price }) => (
          <div key={id}>
            <p>{name}</p>
            <p>{price}</p>
            <hr />
          </div>
        ))
      )}
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const response = await fetch(
    "https://us-central1-medstore-eaba8.cloudfunctions.net/app/products"
  );
  const { product } = await response.json();
  return {
    props: {
      product,
    }, // will be passed to the page component as props
  };
};
